### PR TITLE
Fix parameter copy ctor

### LINKED ISSUE #19: JetVertexRefiner
Dear LCFIPlus developers, 

I have encountered memory allocation(malloc) error with running JetVertexRefiner( I have used ilcsoft release /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-01/ ). You can find steering file what I have used and log file attached in zip archive. 
[Files.zip](https://github.com/lcfiplus/LCFIPlus/files/902261/Files.zip)

### PR DESCRIPTION
**Pull request by andresailer**
I think this fixes #19 

Edit: minimal changes now, only the map must _not_ be copied, because the assignment operator calls `clear`, which otherwise deletes the objects from the shallow copy, not a problem if the map is empty.

~~~I properly implemented the copy constructor for the parameters object because it gets copied and the instances of the parameters were deleted multiple times, because only a shallow copy was done.~~~

~~~I didn't implement the copy for arbitrary classes, because it wasn't used in the configuration I was testing with. Is this needed?~~~

Also fixed something in the `remove` and `clear` function were two times the double cases existed but never the float



BEGINRELEASENOTES
- lcfiplus::Parameters: fix implementation of the copy constructor, fixes lcfiplus/LCFIPlus#19 

ENDRELEASENOTES

### CODE REVIEW

**Comment by jstrube** [comment]
All tests pass and I have tested locally that this takes care of #19.
Pinging @suehara for a final confirmation, but looks good to me.

Thank you for taking this on.

File: include/lcfiplus.h [hunk 1]
```diff
@@ -162,10 +162,34 @@ class Parameters {
   }
   // copy operator/constructor
   Parameters(const Parameters& ref)
-  : _map(ref._map)
+  : _map()
   , _allowstring(ref._allowstring)
   {
-    *this = ref;
```
Comment (andresailer) [inline include/lcfiplus.h]: I think this is calling the assignment operator, which should have done the deep copy as well.
I'll have another look at this.

**Comment by andresailer** [comment]
Updated implementation.

**Comment by jstrube** [comment]
Looks good to merge.
@tomohikosan @suehara @MasakazuKurata any comments?
If not, I'd like to merge before the end of the week.

**Comment by andresailer** [comment]
@jstrube @tomohikosan @suehara @MasakazuKurata 
Can this be merged now?
Thanks 👍

**Comment by jstrube** [comment]
@andresailer is this urgent? I haven't heard from another dev and the week isn't over, yet.

**Comment by andresailer** [comment]
It is over for me...
